{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.neovim-extended;
  langCfg = config.programs.languages;

  # Servers that need their settings wrapped under the server name
  namespacedServers = [
    "rust_analyzer"
    "nixd"
  ];

  needsNamespace = serverName: lib.elem serverName namespacedServers;

  getNamespaceKey = serverName: if serverName == "rust_analyzer" then "rust-analyzer" else serverName;

  builtinServers = [
    "rust-analyzer"
    "clangd"
    "gopls"
    "pylsp"
    "typescript-language-server"
    "yaml-language-server"
    "zls"
    "nixd"
  ];

  getServerCommand =
    attrName: server:
    if server.command != null then
      server.command
    else if lib.elem attrName builtinServers then
      attrName
    else
      null;

  allServers = lib.foldl' (acc: langCfg: acc // langCfg.servers) { } (
    lib.attrValues (lib.filterAttrs (_: l: l.enable) langCfg.languages)
  );
  enabledServers = lib.filterAttrs (_: s: s.enable) allServers;

  validServers = lib.filterAttrs (
    attrName: server:
    let
      cmd = getServerCommand attrName server;
    in
    cmd != null
  ) enabledServers;

  generateServerLua =
    attrName: server:
    let
      serverName = server.name;
      cmd = getServerCommand attrName server;
      cmdParts = [ cmd ] ++ server.args;
      cmdLua = ''cmd = { ${lib.concatMapStringsSep ", " (s: ''"${s}"'') cmdParts} },'';

      rawSettings = server.config;
      settings =
        if rawSettings == { } then
          { }
        else if needsNamespace serverName then
          { ${getNamespaceKey serverName} = rawSettings; }
        else
          rawSettings;

      settingsLua = if settings == { } then "" else "settings = ${lib.generators.toLua { } settings},";
    in
    ''
      lspconfig.${serverName}.setup({
        ${cmdLua}
        ${settingsLua}
        capabilities = capabilities,
      })
    '';

  # LSP servers configuration (generated from unified language config)
  lspServersLua = ''
    -- Auto-generated by neovim-extended.nix
    -- Do not edit manually

    local lspconfig = require('lspconfig')
    local capabilities = require('cmp_nvim_lsp').default_capabilities()

    ${lib.concatStringsSep "\n" (lib.mapAttrsToList generateServerLua validServers)}
  '';

in
{
  options.programs.neovim-extended = {
    enable = lib.mkEnableOption "extended neovim configuration with LSP from unified language config";
  };

  config = lib.mkIf cfg.enable {
    xdg.configFile = {
      # Copy all static Lua files
      "nvim/lua" = {
        source = ./lua;
        recursive = true;
      };
      "nvim/init.lua".source = ./init.lua;

      # LSP servers config is generated from Nix
      "nvim/lua/lsp-servers.lua".text = lspServersLua;
    };

    programs.neovim = {
      enable = true;
      viAlias = true;
      vimAlias = true;
      defaultEditor = false;

      plugins = with pkgs.vimPlugins; [
        # LSP
        nvim-lspconfig

        # Completion
        nvim-cmp
        cmp-nvim-lsp
        cmp-buffer
        cmp-path
        luasnip
        cmp_luasnip

        # Syntax
        nvim-treesitter.withAllGrammars

        # UI
        lualine-nvim
        catppuccin-nvim

        # Navigation
        telescope-nvim
        telescope-fzf-native-nvim
        plenary-nvim

        # Learning keybindings
        which-key-nvim
        hardtime-nvim
      ];

      # No extraLuaConfig needed - init.lua handles everything
    };

    # Enable unified language config
    programs.languages.enable = true;
  };
}
