-- Neovim configuration entry point
-- Loads all configuration modules

-- Core settings first
require('options')
require('keymaps')

-- Theme setup (with dark-mode integration)
require('theme').setup()

-- Plugin configurations
require('completion')
require('treesitter')
require('telescope')
require('lualine')
require('which-key')
require('hardtime')
require('diagnostics')

-- LSP servers (generated by Nix)
require('lsp-servers')
